In [ ]:
import numpy as np

In [35]:
a = np.array([1, 2, 2])
b = np.array([[2], 
              [3], 
              [2]])
print(b.T)

[[2 3 2]]


In [10]:
print(type(a))
print(a.shape)
print(b.shape)

<class 'numpy.ndarray'>
(3,)
(3, 1)


In [27]:
c = np.array([ 10 for _ in range(3)])

In [29]:
print(c, c.shape)
print(c.reshape(3, 1))

[10 10 10] (3,)
[[10]
 [10]
 [10]]


In [26]:
e = np.zeros((3, 5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
d  = np.ones((3, 1))
print(d)



[[1.]
 [1.]
 [1.]]


In [ ]:
c + d

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [34]:
print(c.shape, d.shape)
c @ d

(3,) (3, 1)


array([30.])

In [36]:
#  bài 2

In [43]:
arr = np.array([1 , -2 , 3 , -4 , 5 , -6])
arr > 0

array([ True, False,  True, False,  True, False])

In [48]:
new_arr = np.where(arr > 0, 1, 0)

In [49]:
new_arr

array([1, 0, 1, 0, 1, 0])

In [166]:
new_arr = np.where(arr % 2 == 0, 'even', 'odd')
new_arr

array(['odd', 'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [75]:
arr > 2
new_arr = np.where(arr > 2, 1, 0)
print(new_arr)

[0 0 1 0 1 0]


In [76]:
# bài 3

In [80]:
# Mảng nhiệt độ
temps = np.array([25, 28, 30, 22, 35, 18, 20])
# Danh sách điều kiện
conditions = [
    temps < 20,                    
    (temps >= 20) & (temps < 30),  
    temps >= 30                   
]

categories = ["Cold", "Mild", "Hot"]

classified_temps = np.select(conditions, categories, default="Unk")

print(classified_temps)

['Mild' 'Mild' 'Hot' 'Mild' 'Hot' 'Cold' 'Mild']


In [109]:
mat = np . random . randint (1 ,100 , (5 ,5) )
mat.shape

(5, 5)

In [84]:
mat

array([[62,  3, 89, 47, 65],
       [10, 96, 35, 55, 18],
       [42, 14, 88,  5, 23],
       [55, 57, 47, 47, 88],
       [69, 42,  6, 39, 81]])

In [161]:
# Chuẩn hóa từng hàng (trừ đi min, chia cho max - min)
mean = np.mean(mat, axis=1)
max_value = np.max(mat, axis=1)
min_value = np.min(mat, axis=1)

In [92]:
norm = (mat - mean) / (max_value - min_value)

In [93]:
norm

array([[ 0.10232558, -0.4627907 ,  0.65783133, -0.28780488,  0.23466667],
       [-0.50232558,  0.61860465,  0.00722892, -0.09268293, -0.392     ],
       [-0.13023256, -0.33488372,  0.64578313, -1.31219512, -0.32533333],
       [ 0.02093023,  0.16511628,  0.15180723, -0.28780488,  0.54133333],
       [ 0.18372093, -0.00930233, -0.34216867, -0.48292683,  0.448     ]])

In [165]:
# Áp dụng hàm softmax theo cột:

one = np.ones(5)
sigma = one @ norm
softmax = norm / sigma

In [107]:
softmax

array([[-3.14285714e-01,  1.99000000e+01,  5.87096774e-01,
         1.16831683e-01,  4.63157895e-01],
       [ 1.54285714e+00, -2.66000000e+01,  6.45161290e-03,
         3.76237624e-02, -7.73684211e-01],
       [ 4.00000000e-01,  1.44000000e+01,  5.76344086e-01,
         5.32673267e-01, -6.42105263e-01],
       [-6.42857143e-02, -7.10000000e+00,  1.35483871e-01,
         1.16831683e-01,  1.06842105e+00],
       [-5.64285714e-01,  4.00000000e-01, -3.05376344e-01,
         1.96039604e-01,  8.84210526e-01]])

In [108]:
softmax.shape

(5, 5)

In [110]:
# bài 5

In [144]:
data = np . array ([
    [1, 2, np.nan] ,
    [4, np.nan, 6] ,
    [7, 8, 9]
])
np.isnan(data)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [152]:
# Thay các giá trị NaN bằng trung bình cột
new_data = np.where(np.isnan(data), np.nanmean(data, axis=0), data)

In [153]:
new_data

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [158]:
# Tính z-score cho mỗi cột
mean = np.mean(new_data, axis=0)
var = (np.var(new_data, axis=0))
Z_score = (new_data - mean) / var

In [159]:
Z_score

array([[-0.5, -0.5,  0. ],
       [ 0. ,  0. , -1. ],
       [ 0.5,  0.5,  1. ]])

In [160]:
# Chuẩn hóa min-max theo cột
min = np.min(new_data, axis=0)
max = np.max(new_data, axis=0)

Min_max_scaling = (new_data - min) / (max - min)
Min_max_scaling


array([[0. , 0. , 0.5],
       [0.5, 0.5, 0. ],
       [1. , 1. , 1. ]])