In [1]:
import torch
import numpy as np 

In [9]:
arr = np.array([7]*12).reshape(3,4)
tensor = torch.tensor(arr) 
print(tensor)

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]], dtype=torch.int32)


In [11]:
arr1 = torch.arange(0, 10, 2)
print(arr1)

tensor([0, 2, 4, 6, 8])


In [20]:
tensor1 = torch.randn(2, 3)
print(tensor1)

tensor([[-0.0458,  1.0224, -2.1747],
        [ 0.7049,  0.7114,  1.1532]])


In [21]:
A = torch.arange(12).reshape(3, 4)
print(A)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [27]:
A[:1, :]

tensor([[0, 1, 2, 3]])

In [32]:
A[2:, :]

tensor([[ 8,  9, 10, 11]])

In [39]:
A[:1, 1:2]

tensor([[1]])

In [44]:
A[:-1, 2:]

tensor([[2, 3],
        [6, 7]])

In [48]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5], [6]])
print('tensor A: \n', A)
print('tensor B: \n', B)
print('tensor A + B: \n', A + B)

tensor A: 
 tensor([[1, 2],
        [3, 4]])
tensor B: 
 tensor([[5],
        [6]])
tensor A + B: 
 tensor([[ 6,  7],
        [ 9, 10]])


In [50]:
A*B

tensor([[ 5, 10],
        [18, 24]])

In [51]:
A@B

tensor([[17],
        [39]])

In [49]:
A.view(1, 1, 2, 2)

tensor([[[[1, 2],
          [3, 4]]]])

In [53]:
C = torch.rand(6)
print(C)

tensor([0.6222, 0.3524, 0.5644, 0.3795, 0.2770, 0.9330])


In [54]:
C.view(6,1)

tensor([[0.6222],
        [0.3524],
        [0.5644],
        [0.3795],
        [0.2770],
        [0.9330]])

In [55]:
C.reshape(2, 3)

tensor([[0.6222, 0.3524, 0.5644],
        [0.3795, 0.2770, 0.9330]])

In [68]:
device = torch.cuda.is_available()

In [59]:
C.cuda()

tensor([0.6222, 0.3524, 0.5644, 0.3795, 0.2770, 0.9330], device='cuda:0')

In [60]:
C.cpu()

tensor([0.6222, 0.3524, 0.5644, 0.3795, 0.2770, 0.9330])

In [70]:
C.to(device)

tensor([True, True, True, True, True, True])

In [71]:
C

tensor([0.6222, 0.3524, 0.5644, 0.3795, 0.2770, 0.9330], device='cuda:0')

In [75]:
C.cpu()

tensor([0.6222, 0.3524, 0.5644, 0.3795, 0.2770, 0.9330])