In [1]:
import torch 
import numpy as np

In [8]:
x = torch.tensor([1., 2., 3.])
print(x)
x.add_(0.14)

tensor([1., 2., 3.])


tensor([1.1400, 2.1400, 3.1400])

In [11]:
x.mul_(2)

tensor([2.2800, 4.2800, 6.2800])

In [12]:
x.fill_(10)

tensor([10., 10., 10.])

In [28]:
A = torch.arange(1, 5).reshape(2, 2)
A

tensor([[1, 2],
        [3, 4]])

In [23]:
print(A.sum(axis=0))

tensor([4, 6])


In [31]:
print(A.sum(axis=1, keepdim=True))

tensor([[3],
        [7]])


In [53]:
B = torch.rand(3, 3)
print(B)
mask = B > 0.5
print(B[mask])

tensor([[0.2224, 0.1300, 0.3521],
        [0.7190, 0.7179, 0.1225],
        [0.9990, 0.5935, 0.7430]])
tensor([0.7190, 0.7179, 0.9990, 0.5935, 0.7430])


In [56]:
C = torch.tensor([-1, 6, 3, -4, -3])
print(torch.where(C > 0, C, torch.zeros_like(C)))

tensor([0, 6, 3, 0, 0])


In [67]:
input = torch.tensor([[1, 2], [3, 4]])
index = torch.tensor([[0, 0], [1, 0]])
result = torch.gather(input, dim=1, index=index)

print(result)


tensor([[1, 1],
        [4, 3]])


In [4]:
batch1 = torch.tensor([[[1, 2], [3, 4]]])    # shape [1, 2, 2]
batch2 = torch.tensor([[[5, 6], [7, 8]]])    # shape [1, 2, 2]

output = torch.bmm(batch1, batch2)

print(output)

tensor([[[19, 22],
         [43, 50]]])


In [6]:
batch1 = torch.tensor([[1, 2], [3, 4]])    
batch2 = torch.tensor([[5, 6], [7, 8]])    
print(torch.matmul(batch1, batch2))

tensor([[19, 22],
        [43, 50]])
